Repository pauwels-labs/redact-client, pull requests merged in 2021-07, with the labels that each got.

#32 feat: integrate full e2ee
  .lighthouse/jenkins-x/build-alpine.yaml
  .lighthouse/jenkins-x/build-prod.yaml
  Cargo.lock
  Cargo.toml
  README.md
  src/error_handler.rs
  src/main.rs
  src/render.rs
  src/routes.rs
  src/routes/data/get.rs
  src/routes/data/post.rs
  src/routes/error.rs
  static/secure.handlebars
  static/unsecure.handlebars
Labels: approved, size/XXL

#31 js messaging to parent when data is submitted
  static/secure.handlebars
  static/unsecure.handlebars
Labels: size/M

#33 feat: Add a HTTP client w/ mutual TLS to communicate with a host website
  Cargo.lock
  Cargo.toml
  src/error_handler.rs
  src/main.rs
  src/relayer.rs
  src/routes.rs
  src/routes/data/post.rs
  src/routes/error.rs
  src/routes/proxy.rs
Labels: size/L

#34 JS Custom Messaging
  Cargo.lock
  Cargo.toml
  src/error_handler.rs
  src/render.rs
  src/routes/data.rs
  src/routes/data/get.rs
  src/routes/data/post.rs
  src/routes/error.rs
  static/secure.handlebars
  static/unsecure.handlebars
Labels: approved, size/L

#36 feat: Check for same root domain on proxy request
  Cargo.lock
  Cargo.toml
  src/error.rs
  src/routes/proxy.rs
Labels: approved, size/L
