Repository pauwels-labs/redact-client, pull requests merged in 2021-05, with the labels that each got.

#14 feat: search for public keys
  .lighthouse/jenkins-x/pullrequest.yaml
  Cargo.lock
  Cargo.toml
  OWNERS
  OWNERS_ALIASES
  config/config.yaml
  keys/public/test.pub
  src/crypto.rs
  src/fs_io.rs
  src/main.rs
Labels: size/XL

#15 feat: add support for loading private and public keys
  .gitignore
  config/config.yaml
  keys/public/test.pub
  src/crypto.rs
  src/fs_io.rs
  src/main.rs
Labels: approved, size/L

#16 Switch from MIT to GPL v3
  LICENSE
Labels: approved, size/XL

#19 build: trigger pr
  new-file
Labels: approved, size/XS

#20 build: remove new-file
  new-file
Labels: approved, size/XS

#21 fix: change key length to 32 bit
  src/crypto.rs
  src/main.rs
Labels: approved, size/S

#22 feat: refactor app to integrate new architecture
  .lighthouse/jenkins-x/release.yaml
  Cargo.lock
  Cargo.toml
  README.md
  config/config.yaml
  src/crypto.rs
  src/fs_io.rs
  src/main.rs
  src/render.rs
  src/routes.rs
  src/routes/data.rs
  src/routes/data/get.rs
  src/routes/data/post.rs
  src/routes/error.rs
  src/storage.rs
  static/secure.handlebars
  static/unsecure.handlebars
Labels: approved, size/XXL

#23 build: update rust-config dependency
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: approved, size/M
